#RESPALDO POR SI EL CODIGO SE VA A LA CACA

#Constantes
ANCHO_VENTANA=800
ALTO_VENTANA=600
FPS = 60
ANCHO_BOTON=300
ALTO_BOTON=80
BOTON_X=ANCHO_VENTANA // 2 - ANCHO_BOTON // 2
BOTON_Y=ALTO_VENTANA // 2 + 50
ANCHO_PERSONAJE=40
ALTO_PERSONAJE=80
PERSONAJE_X_INICIAL=140
PERSONAJE_Y_INICIAL=ALTO_VENTANA // 2 - 48
ANCHO_JEFE=55
ALTO_JEFE=120
JEFE_X_INICIAL=ANCHO_VENTANA - ANCHO_JEFE - 160
JEFE_Y_INICIAL=PERSONAJE_Y_INICIAL + ALTO_PERSONAJE - ALTO_JEFE
ANCHO_BARRA=ANCHO_VENTANA
ALTO_BARRA=90
BARRA_Y=ALTO_VENTANA - ALTO_BARRA
ANCHO_BOTON_ATACAR=220
ALTO_BOTON_ATACAR=50
BOTON_ATACAR_X=ANCHO_VENTANA // 2 - ANCHO_BOTON_ATACAR // 2
BOTON_ATACAR_Y=BARRA_Y + 20